#What is Pandas?
Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

#Prerequsites
Youâ€™ll need to know a bit of Python. For a refresher, see the [Python tutorial](https://docs.python.org/tutorial/).

In [1]:
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2022.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

#Object creation

See the [introduction to data structures](https://pandas.pydata.org/docs/user_guide/dsintro.html#dsintro) section of Pandas documentation for details.

You can create a [Series](https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series) (One-dimensional ndarray with axis labels, including time series) by passing a list of values, letting pandas create a default integer index:

In [2]:
import numpy as np
import pandas as pd
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

You can create a [DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame) (Two-dimensional, size-mutable, potentially heterogeneous tabular data) by passing a NumPy array, with a datetime index and labeled columns:

In [3]:
# Returns the range of equally spaced time points
dates = pd.date_range("20220306", periods=6)
dates

DatetimeIndex(['2022-03-06', '2022-03-07', '2022-03-08', '2022-03-09',
               '2022-03-10', '2022-03-11'],
              dtype='datetime64[ns]', freq='D')

In [4]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2022-03-06 -0.984987  1.618522 -0.064563  0.201655
2022-03-07  0.472380 -0.576814  0.284350  0.722739
2022-03-08 -1.527865 -1.252510  0.425970  1.108105
2022-03-09  1.891287  1.569923 -0.842633 -0.457980
2022-03-10 -0.252152 -0.210580 -1.484571 -1.375105
2022-03-11 -0.378655  0.386623 -0.457472  0.746205

You can also create a DataFrame by passing a dictionary of objects that can be converted into a series-like structure:

In [5]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

The columns of the resulting DataFrame have different dtypes:

In [6]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

#Viewing data

See [Essentail basic functionality](https://pandas.pydata.org/docs/user_guide/basics.html#basics) section of Pandas documentation for details.

You can view the top and bottom rows of the frame:

In [7]:
df.head(3) # first three rows

                   A         B         C         D
2022-03-06 -0.984987  1.618522 -0.064563  0.201655
2022-03-07  0.472380 -0.576814  0.284350  0.722739
2022-03-08 -1.527865 -1.252510  0.425970  1.108105

In [8]:
df.tail(2) # last two rows

                   A         B         C         D
2022-03-10 -0.252152 -0.210580 -1.484571 -1.375105
2022-03-11 -0.378655  0.386623 -0.457472  0.746205

You can display the indexes and columns:

In [9]:
df.index

DatetimeIndex(['2022-03-06', '2022-03-07', '2022-03-08', '2022-03-09',
               '2022-03-10', '2022-03-11'],
              dtype='datetime64[ns]', freq='D')

In [10]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

**describe**() shows a quick statistic summary of your data:

In [11]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.129999  0.255861 -0.356486  0.157603
std    1.200853  1.165058  0.724878  0.927293
min   -1.527865 -1.252510 -1.484571 -1.375105
25%   -0.833404 -0.485255 -0.746343 -0.293071
50%   -0.315403  0.088022 -0.261018  0.462197
75%    0.291247  1.274098  0.197122  0.740339
max    1.891287  1.618522  0.425970  1.108105

Transposing your data:

In [12]:
df.T

   2022-03-06  2022-03-07  2022-03-08  2022-03-09  2022-03-10  2022-03-11
A   -0.984987    0.472380   -1.527865    1.891287   -0.252152   -0.378655
B    1.618522   -0.576814   -1.252510    1.569923   -0.210580    0.386623
C   -0.064563    0.284350    0.425970   -0.842633   -1.484571   -0.457472
D    0.201655    0.722739    1.108105   -0.457980   -1.375105    0.746205

[Sorting](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_index.html) by axis:

In [13]:
# The axis along which to sort. The value 0 identifies the rows, and 1 identifies the columns.
df.sort_index(axis=1, ascending=False) # Sort based on column label

                   D         C         B         A
2022-03-06  0.201655 -0.064563  1.618522 -0.984987
2022-03-07  0.722739  0.284350 -0.576814  0.472380
2022-03-08  1.108105  0.425970 -1.252510 -1.527865
2022-03-09 -0.457980 -0.842633  1.569923  1.891287
2022-03-10 -1.375105 -1.484571 -0.210580 -0.252152
2022-03-11  0.746205 -0.457472  0.386623 -0.378655

[Sorting](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html#pandas.DataFrame.sort_values) by values:

In [14]:
df.sort_values(by="C") # Sort by 'C' column ascending

                   A         B         C         D
2022-03-10 -0.252152 -0.210580 -1.484571 -1.375105
2022-03-09  1.891287  1.569923 -0.842633 -0.457980
2022-03-11 -0.378655  0.386623 -0.457472  0.746205
2022-03-06 -0.984987  1.618522 -0.064563  0.201655
2022-03-07  0.472380 -0.576814  0.284350  0.722739
2022-03-08 -1.527865 -1.252510  0.425970  1.108105

#Selection

See [Indexing and Selecting Data](https://pandas.pydata.org/docs/user_guide/indexing.html#indexing) section of Pandas documentation for details.

Selecting a single column, which yields a Series, equivalent to df.A:

In [15]:
df["A"] # Select 'A' column

2022-03-06   -0.984987
2022-03-07    0.472380
2022-03-08   -1.527865
2022-03-09    1.891287
2022-03-10   -0.252152
2022-03-11   -0.378655
Freq: D, Name: A, dtype: float64

Selecting via [], which slices the rows:

In [16]:
df[0:4] # Select first 4 rows

                   A         B         C         D
2022-03-06 -0.984987  1.618522 -0.064563  0.201655
2022-03-07  0.472380 -0.576814  0.284350  0.722739
2022-03-08 -1.527865 -1.252510  0.425970  1.108105
2022-03-09  1.891287  1.569923 -0.842633 -0.457980

In [17]:
df["20220306":"20220310"] # Get "2022-03-06" through "2022-03-10" rows

                   A         B         C         D
2022-03-06 -0.984987  1.618522 -0.064563  0.201655
2022-03-07  0.472380 -0.576814  0.284350  0.722739
2022-03-08 -1.527865 -1.252510  0.425970  1.108105
2022-03-09  1.891287  1.569923 -0.842633 -0.457980
2022-03-10 -0.252152 -0.210580 -1.484571 -1.375105

##Selection by label

**loc** selects rows and columns with specific labels. **iloc** selects rows and columns at specific integer positions.

Getting a cross section using a label:

In [18]:
dates

DatetimeIndex(['2022-03-06', '2022-03-07', '2022-03-08', '2022-03-09',
               '2022-03-10', '2022-03-11'],
              dtype='datetime64[ns]', freq='D')

In [25]:
df.loc[dates[0]] # Get row indexed by '2022-03-06'

A   -0.984987
B    1.618522
C   -0.064563
D    0.201655
Name: 2022-03-06 00:00:00, dtype: float64

Selecting on a multi-axis by label:

In [26]:
df.loc[:, ["A", "B"]] # Get 'A' and 'B' columns for all rows

                   A         B
2022-03-06 -0.984987  1.618522
2022-03-07  0.472380 -0.576814
2022-03-08 -1.527865 -1.252510
2022-03-09  1.891287  1.569923
2022-03-10 -0.252152 -0.210580
2022-03-11 -0.378655  0.386623

Showing label slicing, both endpoints are included:

In [27]:
df.loc["20220307":"20220309", ["A", "B"]] # # Get 'A' and 'B' columns for rows indexed by '2022-03-07' through '2022-03-09'

                   A         B
2022-03-07  0.472380 -0.576814
2022-03-08 -1.527865 -1.252510
2022-03-09  1.891287  1.569923

Reduction in the dimensions of the returned object:

In [28]:
df.loc["20220308", ["A", "B"]] # Get 'A' and 'B' columns of '2022-03-08' row

A   -1.527865
B   -1.252510
Name: 2022-03-08 00:00:00, dtype: float64

Getting a scalar value:

In [29]:
df.loc[dates[0], "A"] # Get value at dates[0] row and 'A' column.

-0.9849872744547663

Getting fast access to a scalar (equivalent to the prior method):

In [30]:
df.at[dates[0], "A"]

-0.9849872744547663

##Selection by position
Selecting via the position of the passed integers:

In [31]:
df.iloc[2] # Get all values of third row

A   -1.527865
B   -1.252510
C    0.425970
D    1.108105
Name: 2022-03-08 00:00:00, dtype: float64

By integer slices, similar to NumPy/Python:

In [32]:
df

                   A         B         C         D
2022-03-06 -0.984987  1.618522 -0.064563  0.201655
2022-03-07  0.472380 -0.576814  0.284350  0.722739
2022-03-08 -1.527865 -1.252510  0.425970  1.108105
2022-03-09  1.891287  1.569923 -0.842633 -0.457980
2022-03-10 -0.252152 -0.210580 -1.484571 -1.375105
2022-03-11 -0.378655  0.386623 -0.457472  0.746205

In [33]:
df.iloc[3:5, 0:2] # Get values of 4 and 5 rows, 'A', 'B' columns

                   A         B
2022-03-09  1.891287  1.569923
2022-03-10 -0.252152 -0.210580

By lists of integer position locations, similar to the NumPy/Python style:

In [34]:
df.iloc[[1, 2, 4], [0, 2]] # Get values of 2, 3, 5 rows, 'A', 'C' columns

                   A         C
2022-03-07  0.472380  0.284350
2022-03-08 -1.527865  0.425970
2022-03-10 -0.252152 -1.484571

Slicing rows explicitly:

In [35]:
df.iloc[1:3, :] # Get values of 2 and 3 rows

                   A         B        C         D
2022-03-07  0.472380 -0.576814  0.28435  0.722739
2022-03-08 -1.527865 -1.252510  0.42597  1.108105

Slicing columns explicitly:

In [36]:
df.iloc[:, 1:3] # Get values of 2 and 3 columns

                   B         C
2022-03-06  1.618522 -0.064563
2022-03-07 -0.576814  0.284350
2022-03-08 -1.252510  0.425970
2022-03-09  1.569923 -0.842633
2022-03-10 -0.210580 -1.484571
2022-03-11  0.386623 -0.457472

 Getting a value explicitly:

In [37]:
df.iloc[1, 1] # Get value at 2nd row and 2nd columns

-0.5768136525744828

Getting fast access to a scalar (equivalent to the prior method):

In [38]:
df.iat[1, 1]

-0.5768136525744828

##Boolean indexing
Using a single columnâ€™s values to select data:

In [39]:
df[df["A"] > 0] # Get rows where 'A' columns is greater than 0

                   A         B         C         D
2022-03-07  0.472380 -0.576814  0.284350  0.722739
2022-03-09  1.891287  1.569923 -0.842633 -0.457980

Using the isin() method for filtering:

In [40]:
df2 = df.copy()
df2["E"] = ["one", "one", "two", "three", "four", "three"] # Add new column 'E'
df2

                   A         B         C         D      E
2022-03-06 -0.984987  1.618522 -0.064563  0.201655    one
2022-03-07  0.472380 -0.576814  0.284350  0.722739    one
2022-03-08 -1.527865 -1.252510  0.425970  1.108105    two
2022-03-09  1.891287  1.569923 -0.842633 -0.457980  three
2022-03-10 -0.252152 -0.210580 -1.484571 -1.375105   four
2022-03-11 -0.378655  0.386623 -0.457472  0.746205  three

In [41]:
df2[df2["E"].isin(["two", "four"])] # Get rows where the values in column 'E' is either "two" or "four"

                   A        B         C         D     E
2022-03-08 -1.527865 -1.25251  0.425970  1.108105   two
2022-03-10 -0.252152 -0.21058 -1.484571 -1.375105  four

##Setting
Setting a new column automatically aligns the data by the indexes:

In [43]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range("20220306", periods=6))
s1

2022-03-06    1
2022-03-07    2
2022-03-08    3
2022-03-09    4
2022-03-10    5
2022-03-11    6
Freq: D, dtype: int64

In [44]:
df["F"] = s1
df

                   A         B         C         D  F
2022-03-06 -0.984987  1.618522 -0.064563  0.201655  1
2022-03-07  0.472380 -0.576814  0.284350  0.722739  2
2022-03-08 -1.527865 -1.252510  0.425970  1.108105  3
2022-03-09  1.891287  1.569923 -0.842633 -0.457980  4
2022-03-10 -0.252152 -0.210580 -1.484571 -1.375105  5
2022-03-11 -0.378655  0.386623 -0.457472  0.746205  6

Setting values by label:

In [45]:
df.at[dates[0], "A"] = 0 # Set the value at dates[0] and 'A' column to be 0
df

                   A         B         C         D  F
2022-03-06  0.000000  1.618522 -0.064563  0.201655  1
2022-03-07  0.472380 -0.576814  0.284350  0.722739  2
2022-03-08 -1.527865 -1.252510  0.425970  1.108105  3
2022-03-09  1.891287  1.569923 -0.842633 -0.457980  4
2022-03-10 -0.252152 -0.210580 -1.484571 -1.375105  5
2022-03-11 -0.378655  0.386623 -0.457472  0.746205  6

Setting values by position:

In [46]:
df.iat[0, 1] = 0 # Set the value at first row, second column to be 0
df

                   A         B         C         D  F
2022-03-06  0.000000  0.000000 -0.064563  0.201655  1
2022-03-07  0.472380 -0.576814  0.284350  0.722739  2
2022-03-08 -1.527865 -1.252510  0.425970  1.108105  3
2022-03-09  1.891287  1.569923 -0.842633 -0.457980  4
2022-03-10 -0.252152 -0.210580 -1.484571 -1.375105  5
2022-03-11 -0.378655  0.386623 -0.457472  0.746205  6

Setting by assigning with a NumPy array:

In [47]:
df.loc[:, "D"] = np.array([5] * len(df)) # Set the values at 'D' columns to be 5
df

                   A         B         C  D  F
2022-03-06  0.000000  0.000000 -0.064563  5  1
2022-03-07  0.472380 -0.576814  0.284350  5  2
2022-03-08 -1.527865 -1.252510  0.425970  5  3
2022-03-09  1.891287  1.569923 -0.842633  5  4
2022-03-10 -0.252152 -0.210580 -1.484571  5  5
2022-03-11 -0.378655  0.386623 -0.457472  5  6

#Missing data

See [Missing Data](https://pandas.pydata.org/docs/user_guide/missing_data.html#missing-data) section of Pandas documentation for details.

Pandas primarily uses the value np.nan to represent missing data. It is by default not included in computations.

In [48]:
# Reindexing allows you to change/add/delete the index on a specified axis. This returns a copy of the data:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])
# Add a new column "E" and set the first two rows of "E" to be "1"
df1.loc[dates[0] : dates[1], "E"] = 1
df1

                   A         B         C  D  F    E
2022-03-06  0.000000  0.000000 -0.064563  5  1  1.0
2022-03-07  0.472380 -0.576814  0.284350  5  2  1.0
2022-03-08 -1.527865 -1.252510  0.425970  5  3  NaN
2022-03-09  1.891287  1.569923 -0.842633  5  4  NaN

To drop any rows that have missing data:

In [50]:
df1.dropna(how="any")

                  A         B         C  D  F    E
2022-03-06  0.00000  0.000000 -0.064563  5  1  1.0
2022-03-07  0.47238 -0.576814  0.284350  5  2  1.0

Filling missing data:

In [51]:
df1.fillna(value=5)

                   A         B         C  D  F    E
2022-03-06  0.000000  0.000000 -0.064563  5  1  1.0
2022-03-07  0.472380 -0.576814  0.284350  5  2  1.0
2022-03-08 -1.527865 -1.252510  0.425970  5  3  5.0
2022-03-09  1.891287  1.569923 -0.842633  5  4  5.0

To get the boolean mask where values are *NaN*:

In [52]:
pd.isna(df1)

                A      B      C      D      F      E
2022-03-06  False  False  False  False  False  False
2022-03-07  False  False  False  False  False  False
2022-03-08  False  False  False  False  False   True
2022-03-09  False  False  False  False  False   True

#Operations

See the [Flexible binary operations](https://pandas.pydata.org/docs/user_guide/basics.html#basics-binop) section of Pandas documentation for details.

##Stats
Operations in general exclude missing data.
Performing a descriptive statistic:

In [53]:
df

                   A         B         C  D  F
2022-03-06  0.000000  0.000000 -0.064563  5  1
2022-03-07  0.472380 -0.576814  0.284350  5  2
2022-03-08 -1.527865 -1.252510  0.425970  5  3
2022-03-09  1.891287  1.569923 -0.842633  5  4
2022-03-10 -0.252152 -0.210580 -1.484571  5  5
2022-03-11 -0.378655  0.386623 -0.457472  5  6

In [54]:
df.max(axis=0) # Get max of all columns

A    1.891287
B    1.569923
C    0.425970
D    5.000000
F    6.000000
dtype: float64

Same operation on the other axis:

In [55]:
df.max(axis=1) # Get max of all rows

2022-03-06    5.0
2022-03-07    5.0
2022-03-08    5.0
2022-03-09    5.0
2022-03-10    5.0
2022-03-11    6.0
Freq: D, dtype: float64

##Apply

Applying functions to the data:

In [59]:
df.apply(lambda x: x.max() - x.min()) # Get the min-max differenes of columns

A    3.419152
B    2.822433
C    1.910541
D    0.000000
F    5.000000
dtype: float64

##String Methods
Series is equipped with a set of string processing methods in the str attribute that make it easy to operate on each element of the array, as in the code snippet below. Note that pattern-matching in str generally uses regular expressions by default (and in some cases always uses them).

In [60]:
s = pd.Series(["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

#Getting data in/out
##CSV
Writing to a csv file:

In [61]:
df.to_csv("foo.csv")

Reading from a csv file:

In [62]:
pd.read_csv("foo.csv")

   Unnamed: 0         A         B         C  D  F
0  2022-03-06  0.000000  0.000000 -0.064563  5  1
1  2022-03-07  0.472380 -0.576814  0.284350  5  2
2  2022-03-08 -1.527865 -1.252510  0.425970  5  3
3  2022-03-09  1.891287  1.569923 -0.842633  5  4
4  2022-03-10 -0.252152 -0.210580 -1.484571  5  5
5  2022-03-11 -0.378655  0.386623 -0.457472  5  6

##HDF5

HDF5 is a unique technology suite that makes possible the management of extremely large and complex data collections. If you want to know more about HDF5 format, please see [What is HDF5](https://support.hdfgroup.org/HDF5/whatishdf5.html) for details.

Reading and writing to HDFStores.

In [63]:
df.to_hdf("foo.h5", "df")

Reading from a HDF5 Store:

In [64]:
pd.read_hdf("foo.h5", "df")

                   A         B         C  D  F
2022-03-06  0.000000  0.000000 -0.064563  5  1
2022-03-07  0.472380 -0.576814  0.284350  5  2
2022-03-08 -1.527865 -1.252510  0.425970  5  3
2022-03-09  1.891287  1.569923 -0.842633  5  4
2022-03-10 -0.252152 -0.210580 -1.484571  5  5
2022-03-11 -0.378655  0.386623 -0.457472  5  6

##Excel

Reading and writing to MS Excel.

Writing to an excel file:

In [65]:
df.to_excel("foo.xlsx", sheet_name="Sheet1")

Reading from an excel file:

In [66]:
pd.read_excel("foo.xlsx", "Sheet1", index_col=None, na_values=["NA"])

  Unnamed: 0         A         B         C  D  F
0 2022-03-06  0.000000  0.000000 -0.064563  5  1
1 2022-03-07  0.472380 -0.576814  0.284350  5  2
2 2022-03-08 -1.527865 -1.252510  0.425970  5  3
3 2022-03-09  1.891287  1.569923 -0.842633  5  4
4 2022-03-10 -0.252152 -0.210580 -1.484571  5  5
5 2022-03-11 -0.378655  0.386623 -0.457472  5  6